import collections_function

collections_function.KLM_conversation_start_with_others_function()
collections_function.British_Airways_conversation_start_with_others_function()
collections_function.AirFrance_conversation_start_with_others_function()
collections_function.AmericanAir_conversation_start_with_others_function()
collections_function.Lufthansa_conversation_start_with_others_function()
collections_function.AirBerlin_conversation_start_with_others_function()
collections_function.easyJet_conversation_start_with_others_function()
collections_function.RyanAir_conversation_start_with_others_function()
collections_function.SingaporeAir_conversation_start_with_others_function()
collections_function.Qantas_conversation_start_with_others_function()
collections_function.EtihadAirways_conversation_start_with_others_function()
collections_function.VirginAtlantic_conversation_start_with_others_function()
