import Cleaning_and_presentation_functions

Cleaning_and_presentation_functions.delete_non_english_tweets()
print('delete_non_english_tweets done')
Cleaning_and_presentation_functions.data_preparation()
print('data_preparation done')
Cleaning_and_presentation_functions.is_a_reply()
print('is_a_reply done')
Cleaning_and_presentation_functions.place_object()
print('place_object done')
Cleaning_and_presentation_functions.tweet_object_cleaning()
print('tweet_object_cleaning done')
Cleaning_and_presentation_functions.user_object_cleaning()
print('user_object_cleaning done')
Cleaning_and_presentation_functions.tweet_entities_cleaning()
print('tweet_entities_cleaning done')
Cleaning_and_presentation_functions.entities_cleaning()
print('entities_cleaning done')