import Function_for_every_collection
from index import tweets
import pymongo

tweets.create_index([('id',pymongo.ASCENDING),('is_a_reply',pymongo.ASCENDING)],name='d1')
tweets.create_index([('user.id',pymongo.ASCENDING),('is_a_reply',pymongo.ASCENDING)],name='d3')

print('KLM start')
Function_for_every_collection.KLM_conversation_start_with_others_function()
print('KLM done')
print('British Airways start')
Function_for_every_collection.British_Airways_conversation_start_with_others_function()
print('British Airways done')
print('Air France start')
Function_for_every_collection.AirFrance_conversation_start_with_others_function()
print('Air France done')
print('American Air start')
Function_for_every_collection.AmericanAir_conversation_start_with_others_function()
print('American Air done')
print('Lufthansa start')
Function_for_every_collection.Lufthansa_conversation_start_with_others_function()
print('Lufthansa done')
print('easyJet start')
Function_for_every_collection.easyJet_conversation_start_with_others_function()
print('easyJet done')
print('RyanAir start')
Function_for_every_collection.RyanAir_conversation_start_with_others_function()
print('RyanAir done')
print('Singapore Air start')
Function_for_every_collection.SingaporeAir_conversation_start_with_others_function()
print('Singapore Air done')
print('Quantas start')
Function_for_every_collection.Qantas_conversation_start_with_others_function()
print('Quantas done')
print('Etihad start')
Function_for_every_collection.EtihadAirways_conversation_start_with_others_function()
print('Etihad done')
print('Virgin start')
Function_for_every_collection.VirginAtlantic_conversation_start_with_others_function()
print('Virgin done')